### ISSUE TITLE
budget calculation

### ISSUE THREAD

**Issue by gr2m** [AfricaHackTrip/documentary-film#13]
Hey Alex, I try to put together some information for potential sponsors. Could you make a rough budget calculation, what you'll need to make a proper video documentation of the trip?

**Comment by langalex** [comment]
will do.

**Comment by langalex** [comment]
Here's an estimate put together with the help of on of my film making friends:

## Camera Gear
- Renting a decent camera: if we can get one of the U.S. guys to rent it there and bring it along this could end up being much cheaper than doing it in Europe, e.g. $1500 at lensrentals.com
- lighting: for example http://www.lensrentals.com/rent/video/lighting/continuous-lights/arri-locaster-ac-dc-led - another $500 - lighting is optional, we can always make do with the sun and other light sources
- I have all the other gear (audio recording and accessories)

## Post Production
- Editor - 1000-3000 euro (In berlin you can get cheaper editors, but they will do fewer cuts and take more creative control usually). Editors actually usually charge about 250-450 euro/day
- Sound editor - 200-500 euro . 100/day
- Color grader - try to get an editor with some experience doing this, otherwise I think it can be pretty expensive to hire a separate person to do this. But I would assume it will be at least 200 /day... maybe more. 

## Minimal Scenario

In the minimal scenario we can use my own camera that works but isn't great and I can do the post production myself, so it would essentially cost nothing

## Mid-level setup

In this scenario we would rent a camera and offload some of the post production work
- camera: $1500
- post: €2000

= €3200 + €500 safety margin

## Dream Setup
- camera: $1500
- lights: $500
- post production: €4000

= €5500 + €1000 safety margin

All these calculations assume we can get the gear in the U.S.  Who should we ask about that?

**Comment by gr2m** [comment]
So we currently do not have people coming with us from the US. But there is one I wanted reach out to anyway. How much of a difference would it make to get it from Europe?

**Comment by langalex** [comment]
From what I can tell a huge difference. What about people from GItHub?

**Comment by gr2m** [comment]
Didn't hear back yet. I've to finish the website first to show some progress, then will reach out again.

**Comment by langalex** [comment]
Recently rented from a company in Stockholm and they would want €2357 for the camera. I'm going to prepare something that I can send to Canon to ask if they can sponsor the camera directly.

**Comment by langalex** [comment]
## New cost calculation
- Camera: $1500 when rented in US, €2500 when rented in Europe
- post production: €2000
- safety margin: €500
- camera insurance: pending

= €5000 + insurance when rented in europe, otherwise €3600.

If we can get more money for post production (e.g. €4000) that would mean we can get a professional help us with the editing and all that, which means the film will end up look more professional and just be generally better (the way the footage is edited together having a huge impact on the overall result - something a pro would be much better at than I am).
